[Floor.Floor1]
class = "Floor"
image = ":deeper:tiles/Floor1.png"

[Floor.Floor1e]
class = "Floor"
image = ":deeper:tiles/Floor1e.png"

[Floor.Floor1f]
class = "Floor"
image = ":deeper:tiles/Floor1f.png"